apiVersion: "v1"
kind: Pod
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.name }}
  labels:
    app.kubernetes.io/name: {{ .Values.name }}
spec:
  containers:
    - name: {{ .Values.name }}
      image: {{ .Values.image }}
      env: 
      {{- range $k, $v := .Values.env }}
        - name: {{ $k | quote }}
          value: {{ $v | quote }}
      {{- end }}
      ports:
        - containerPort: {{ .Values.env.port | default 80 }}
